# @package _global_
benchmark_id: OptBench
task_id: ${task.name}
task:
  _target_: carps.utils.task.Task
  name: Schwefel-10
  seed: ${seed}
  objective_function:
    _target_: optbench.functions.Schwefel
    dim: 10
    seed: ${seed}
  input_space:
    _target_: carps.utils.task.InputSpace
    configuration_space:
      _target_: ConfigSpace.configuration_space.ConfigurationSpace.from_serialized_dict
      _convert_: object
      d:
        name: null
        hyperparameters:
        - type: uniform_float
          name: x_0
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_1
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_2
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_3
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_4
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_5
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_6
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_7
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_8
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        - type: uniform_float
          name: x_9
          lower: -500
          upper: 500
          default_value: 0
          log: false
          meta: null
        conditions: []
        forbiddens: []
        python_module_version: 1.2.0
        format_version: 0.4
    fidelity_space:
      _target_: carps.utils.task.FidelitySpace
      is_multifidelity: false
      fidelity_type: null
      min_fidelity: null
      max_fidelity: null
    instance_space: null
  output_space:
    _target_: carps.utils.task.OutputSpace
    n_objectives: 1
    objectives:
    - quality
  optimization_resources:
    _target_: carps.utils.task.OptimizationResources
    n_trials: 147
    time_budget: null
    n_workers: 1
  metadata:
    _target_: carps.utils.task.TaskMetadata
    has_constraints: false
    domain: synthetic
    objective_function_approximation: real
    has_virtual_time: false
    deterministic: true
    dimensions: 10
    search_space_n_categoricals: 0
    search_space_n_ordinals: 0
    search_space_n_integers: 0
    search_space_n_floats: 10
    search_space_has_conditionals: false
    search_space_has_forbiddens: false
    search_space_has_priors: false
